### ISSUE TITLE
Logo Design For Real Estate Manager

### ISSUE THREAD

**Issue by zularizal** [diegomfv/RealEstateManager#1]
Hi @diegomfv , I am a graphic designer. After I review your project, your app is very good. Therefore I suggest a logo and icon for you. If you want it, I will design it for you and it's free.

Best Regards,
Zularizal

**Comment by ritik23-coder** [comment]
Hi, I am a final year btech student I used your code to build the app but your maps aren't working as I am not able to the set my current location and add address of any apartment, whenever I Add the address it says the address is invalid....
